//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeApiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCallLog
    {
        public int Id { get; set; }
        public string ActionMethodName { get; set; }
        public string ControllerName { get; set; }
        public System.DateTime DateTime { get; set; }
        public int UserId { get; set; }
    }
}
